Repository PaloAltoNetworks/terraform-aws-vmseries-modules, pull requests merged in 2021-12, with the labels that each got.

#154 feat(panorama)!: one EC2 VM per one module
  modules/panorama/README.md
  modules/panorama/main.tf
  modules/panorama/outputs.tf
  modules/panorama/variables.tf
Labels: enhancement, aws

#143 feat(vpc_endpoint): add a new module `vpc_endpoint`
  examples/vpc_endpoint/README.md
  examples/vpc_endpoint/example.tfvars
  examples/vpc_endpoint/main.tf
  examples/vpc_endpoint/variables.tf
  examples/vpc_endpoint/versions.tf
  modules/vpc_endpoint/main.tf
  modules/vpc_endpoint/outputs.tf
  modules/vpc_endpoint/variables.tf
  modules/vpc_endpoint/versions.tf
Labels: enhancement

#161 feat(gwlb_endpoint_set): make module `gwlb_endpoint_set` public
  modules/gwlb_endpoint_set/README.md
Labels: documentation, enhancement, aws

#163 feat(transit_gateway_peering): add a new module `transit_gateway_peer…
  .github/workflows/ci.yml
  examples/transit_gateway_peering/example.tfvars
  examples/transit_gateway_peering/main.tf
  examples/transit_gateway_peering/routes.tf
  examples/transit_gateway_peering/variables.tf
  examples/transit_gateway_peering/versions.tf
  modules/transit_gateway_peering/README.md
  modules/transit_gateway_peering/main.tf
  modules/transit_gateway_peering/outputs.tf
  modules/transit_gateway_peering/variables.tf
  modules/transit_gateway_peering/versions.tf
Labels: enhancement, aws
