Repository PaloAltoNetworks/terraform-aws-vmseries-modules, pull requests merged in 2022-11, with the labels that each got.

#232 fix(panorama): Add variable to pass KMS key id
  examples/standalone_panorama/main.tf
  modules/panorama/README.md
  modules/panorama/main.tf
  modules/panorama/variables.tf
Labels: stale

#243 added dedicated resource for allowed_principals on the vpc_endpoint_service
  modules/gwlb/README.md
  modules/gwlb/main.tf
Labels: enhancement, aws

#249 Fix: handle empty data
  modules/asg/main.tf
Labels: bug
